name: Gradle Package

on:
  push:
    tags:
      - '*'

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Generate changelog
        run: /bin/sh ./changes.sh ${{ steps.tag.outputs.tag }} ./changelog.out.md

      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: ./changelog.out.md
          retention-days: 5

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Upload build output (libs)
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: build/libs/*.jar

      - name: Upload build output (devlibs)
        uses: actions/upload-artifact@v3
        with:
          name: devlibs
          path: build/devlibs/*.jar

  publish:
    name: Publish packages & create a release
    runs-on: ubuntu-latest

    steps:
      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: changelog

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download libs
        uses: actions/download-artifact@v3
        with:
          name: libs

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          prerelease: true
          token: ${{ secrets.PA_TOKEN }}
          bodyFile: ./changelog.out.md
